//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public string customerName { get; set; }
        public Nullable<System.DateTime> bookingDate { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string time { get; set; }
        public Nullable<int> venue_id { get; set; }
        public Nullable<int> slot_id { get; set; }
        public string eventName { get; set; }
        public Nullable<int> numberOfPersons { get; set; }
        public string extraArrangement { get; set; }
        public Nullable<int> reciptNumber { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> inserteddatetime { get; set; }
        public Nullable<bool> isBooked { get; set; }
        public Nullable<int> booked_by { get; set; }
        public Nullable<int> numberOfKids { get; set; }
        public string birthdayGirlBoy { get; set; }
        public string meal { get; set; }
        public string theme { get; set; }
        public string addOnShows { get; set; }
        public string tip { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
    }
}
