//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventTransaction
    {
        public int id { get; set; }
        public Nullable<int> booking_id { get; set; }
        public Nullable<int> paymentType { get; set; }
        public Nullable<int> amount { get; set; }
        public string bankName { get; set; }
        public string chequeNumber { get; set; }
        public string creditCardNumber { get; set; }
        public Nullable<System.DateTime> insertedDateTime { get; set; }
        public string remarks { get; set; }
    }
}
