//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cmsEntities4 : DbContext
    {
        public cmsEntities4()
            : base("name=cmsEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<delete_log> delete_log { get; set; }
        public virtual DbSet<eventSetup> eventSetups { get; set; }
        public virtual DbSet<eventSetupsMap> eventSetupsMaps { get; set; }
        public virtual DbSet<eventType> eventTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userScreenChildPermission> userScreenChildPermissions { get; set; }
        public virtual DbSet<userScreenPermission> userScreenPermissions { get; set; }
        public virtual DbSet<venue> venues { get; set; }
        public virtual DbSet<slot> slots { get; set; }
        public virtual DbSet<eventTransaction> eventTransactions { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
    }
}
