//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userScreenPermission
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public bool calendar { get; set; }
        public bool eventSetup { get; set; }
        public bool eventTransaction { get; set; }
        public bool reports { get; set; }
    }
}
